base_global_planner: SBPLLatticePlanner
SBPLLatticePlanner:
  environment_type: XYThetaLattice
  planner_type: ARAPlanner
  allocated_time: 10.0
  initial_epsilon: 5.0
  forward_search: false
  nominalvel_mpersecs: 0.35
  timetoturn45degsinplace_secs: 2.6 # = 0.6 rad/s


